package models

import "time"

type (
	// Release represents a release with all information
	Release struct {
		Version         string
		PreviousVersion string
		Title           string
		Summary         string
		Date            time.Time
		Features        []ReleaseItem
		BugFixes        []ReleaseItem
		Breaking        []ReleaseItem
		Documentation   []ReleaseItem
		Improvements    []ReleaseItem
		Other           []ReleaseItem
		AllCommits      []Commit
		VersionBump     VersionBump
		ClosedIssues    []Issue
		MergedPRs       []PullRequest
		Contributors    []string
		NewContributors []string
		Dependencies    []DependencyChange
		FileStats       FileStatistics
	}

	PullRequest struct {
		Number      int
		Title       string
		Description string
		Author      string
		Labels      []string
		URL         string
	}

	// DependencyChange represents a change in a project dependency
	DependencyChange struct {
		Name       string               // Package name (e.g.: "github.com/user/repo", "react")
		OldVersion string               // Previous version (empty if Type == DependencyAdded)
		NewVersion string               // New version (empty if Type == DependencyRemoved)
		Type       DependencyChangeType // Change type
		Manager    string               // Manager: "go.mod", "package.json", "Cargo.toml", etc.
		Severity   ChangeSeverity       // Severity: major/minor/patch to detect breaking changes
		IsDirect   bool                 // true = direct dependency, false = dev/indirect
	}

	DependencyChangeType string

	ChangeSeverity string

	FileStatistics struct {
		FilesChanged int
		Insertions   int
		Deletions    int
		TopFiles     []FileChange
	}

	FileChange struct {
		Path      string
		Additions int
		Deletions int
	}

	// ReleaseItem represents an item in the changelog
	ReleaseItem struct {
		Type        string // feat, fix, docs, etc
		Scope       string
		Description string
		Breaking    bool
		CommitHash  string
		PRNumber    string // if it has an associated PR
	}

	// VersionBump indicates the version bump type
	VersionBump string

	// ReleaseNotes is the result generated by AI
	ReleaseNotes struct {
		Title           string
		Summary         string
		Highlights      []string
		Sections        []ReleaseNotesSection
		Changelog       string
		Recommended     VersionBump
		QuickStart      string
		Examples        []CodeExample
		BreakingChanges []string
		Comparisons     []Comparison
		Links           map[string]string
		Usage           *TokenUsage
	}

	ReleaseNotesSection struct {
		Title string
		Items []string
	}

	// CodeExample represents a code example with description
	CodeExample struct {
		Title       string // Example title
		Description string // Short description
		Code        string // Example code
		Language    string // Language (bash, go, etc.)
	}

	// Comparison represents a before/after comparison
	Comparison struct {
		Feature string // Feature name
		Before  string // Previous state
		After   string // New state
	}

	VCSRelease struct {
		TagName string
		Name    string
		Body    string
		Draft   bool
		URL     string
	}
)

const (
	MajorBump VersionBump = "major"
	MinorBump VersionBump = "minor"
	PatchBump VersionBump = "patch"
	NoBump    VersionBump = "none"
)

const (
	DependencyAdded   DependencyChangeType = "added"
	DependencyUpdated DependencyChangeType = "updated"
	DependencyRemoved DependencyChangeType = "removed"
)

const (
	MajorChange   ChangeSeverity = "major"
	MinorChange   ChangeSeverity = "minor"
	PatchChange   ChangeSeverity = "patch"
	UnknownChange ChangeSeverity = "unknown"
)
