name: Bug Report
description: Create a report to help us improve MateCommit
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! Your feedback helps make MateCommit better for everyone.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: I was trying to... and then...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Tell us how to reproduce the error.
      placeholder: |
        1. Run `matecommit suggest`
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the commit message to be...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The CLI crashed with error...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Version of MateCommit (run `matecommit --version`)
      placeholder: v1.4.0
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, logs, or any other information that might help.
